# Generated by Django 5.1.7 on 2025-03-18 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_ingredient_alter_user_role_recipe_generaterecipe_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='calories_per_100g',
            field=models.FloatField(null='false', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='carbs_per_100g',
            field=models.FloatField(null='false', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fats_per_100g',
            field=models.FloatField(null='false', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='protein_per_100g',
            field=models.FloatField(null='false', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
