# Generated by Django 5.1.7 on 2025-04-07 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_chefrating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefrating',
            options={'ordering': ['-created_at']},
        ),
    ]
